apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upf
  labels:
    app: free5gc
    nf: upf
    name: upf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: upf
      name: upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: upf
        name: upf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.1/24" ] },
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.1/24" ] }
          ]'
    spec:
      initContainers:
      - name: wait-nrf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: nrf-nnrf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the NRF; sleep 2; done;"]
      containers:
      - name: upf
        image: ghcr.io/niloysh/free5gc:v3.2.0
        imagePullPolicy: Always
        command: [ "/free5gc/config/wrapper.sh" ]
        volumeMounts:
        - mountPath: /free5gc/config/
          name: upf-volume
        ports:
        - containerPort: 8805
          name: n4
          protocol: UDP
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      restartPolicy: Always
      volumes:
      - name: upf-volume
        configMap:
          name: upf-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
